// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://drfnrooyiwdspymtiecx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRyZm5yb295aXdkc3B5bXRpZWN4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc2OTgzMDMsImV4cCI6MjA3MzI3NDMwM30.JEMC-GAdr35Y73jtqMfiui7SQWEpnlFFRTeN1DTnhko";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    // Do not persist sessions between visits so users must login every time they open the site
    persistSession: false,
    autoRefreshToken: false,
  }
});
